//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ToucanParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrToucanParser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ToucanParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IToucanParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ToucanParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] ToucanParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleDeclaration([NotNull] ToucanParser.ModuleDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.importDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportDirective([NotNull] ToucanParser.ImportDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDirective([NotNull] ToucanParser.UsingDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] ToucanParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] ToucanParser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] ToucanParser.StructDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.externalFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternalFunctionDeclaration([NotNull] ToucanParser.ExternalFunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] ToucanParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.classInstanceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInstanceDeclaration([NotNull] ToucanParser.ClassInstanceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] ToucanParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] ToucanParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ToucanParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.exprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStatement([NotNull] ToucanParser.ExprStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.localVarDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVarDeclaration([NotNull] ToucanParser.LocalVarDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.localVarInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVarInitializer([NotNull] ToucanParser.LocalVarInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.forInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitializer([NotNull] ToucanParser.ForInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.forIterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForIterator([NotNull] ToucanParser.ForIteratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] ToucanParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] ToucanParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] ToucanParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] ToucanParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.usingStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingStatement([NotNull] ToucanParser.UsingStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.startThreadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartThreadStatement([NotNull] ToucanParser.StartThreadStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.useThreadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseThreadStatement([NotNull] ToucanParser.UseThreadStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] ToucanParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.syncBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncBlock([NotNull] ToucanParser.SyncBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] ToucanParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] ToucanParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] ToucanParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] ToucanParser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.ternary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTernary([NotNull] ToucanParser.TernaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.logicOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicOr([NotNull] ToucanParser.LogicOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.logicAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicAnd([NotNull] ToucanParser.LogicAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.bitwiseOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOr([NotNull] ToucanParser.BitwiseOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.bitwiseXor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseXor([NotNull] ToucanParser.BitwiseXorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.bitwiseAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseAnd([NotNull] ToucanParser.BitwiseAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality([NotNull] ToucanParser.EqualityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.relational"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational([NotNull] ToucanParser.RelationalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.shift"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift([NotNull] ToucanParser.ShiftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.additive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive([NotNull] ToucanParser.AdditiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.multiplicative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative([NotNull] ToucanParser.MultiplicativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary([NotNull] ToucanParser.UnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] ToucanParser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.arrayExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayExpression([NotNull] ToucanParser.ArrayExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.elementInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementInitialization([NotNull] ToucanParser.ElementInitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.dictionaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryExpression([NotNull] ToucanParser.DictionaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] ToucanParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.memberInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberInitialization([NotNull] ToucanParser.MemberInitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.privateModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrivateModifier([NotNull] ToucanParser.PrivateModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.publicModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPublicModifier([NotNull] ToucanParser.PublicModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.abstractModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractModifier([NotNull] ToucanParser.AbstractModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.staticModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticModifier([NotNull] ToucanParser.StaticModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.initializerExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerExpression([NotNull] ToucanParser.InitializerExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] ToucanParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] ToucanParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.inheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInheritance([NotNull] ToucanParser.InheritanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.callArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallArguments([NotNull] ToucanParser.CallArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.elementAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementAccess([NotNull] ToucanParser.ElementAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.elementIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementIdentifier([NotNull] ToucanParser.ElementIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.argumentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentExpression([NotNull] ToucanParser.ArgumentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.parametersIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametersIdentifier([NotNull] ToucanParser.ParametersIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] ToucanParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ToucanParser.stringPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringPart([NotNull] ToucanParser.StringPartContext context);
}
} // namespace AntlrToucanParser
